apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: taskflow-api
  namespace: taskflow
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: taskflow-api
  namespaceSelector:
    matchNames:
      - taskflow
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
